### PR TITLE
Update goatools to v1.3.1

### PR DESCRIPTION
**Pull request by mencian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by joshuazhuang7** [comment]
@conda-forge-admin please rerender

**Comment by mencian** [comment]
Hi @hadim, can you review these changes when you get a chance?

**Comment by hadim** [comment]
Lgtm. Can you add yourself as maintainer and remove me?

**Comment by mencian** [comment]
Hello @hadim, can I trouble you for a review when you get a chance? I've also added myself to the recipe maintainers section.

**Pull request merged**
